//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Behavior
    {
        public int ID { get; set; }
        public int Ok { get; set; }
        public int Bad { get; set; }
        public int Sleep { get; set; }
        public int GetBook { get; set; }
        public int Sudent_Id { get; set; }
        public int Subject_Id { get; set; }
        public int Week_Id { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Week Week { get; set; }
    }
}
