//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STDEntities : DbContext
    {
        public STDEntities()
            : base("name=STDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Behavior> Behaviors { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Duty> Duties { get; set; }
        public virtual DbSet<RegisterTask> RegisterTasks { get; set; }
        public virtual DbSet<RegisterTest> RegisterTests { get; set; }
        public virtual DbSet<Sharing> Sharings { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Duty> Student_Duty { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Week> Weeks { get; set; }
    }
}
