//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STDEntities : DbContext
    {
        public STDEntities()
            : base("name=STDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence> Absence { get; set; }
        public virtual DbSet<Behavior> Behavior { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Duty> Duty { get; set; }
        public virtual DbSet<RegisterTask> RegisterTask { get; set; }
        public virtual DbSet<RegisterTest> RegisterTest { get; set; }
        public virtual DbSet<Sharing> Sharing { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Student_Duty> Student_Duty { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<Week> Week { get; set; }
    }
}
