//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Duty
    {
        public int Student_Id { get; set; }
        public int Duty_Id { get; set; }
        public bool IsSolved { get; set; }
        public Nullable<int> Memorized { get; set; }
        public Nullable<int> Reading { get; set; }
        public string Note { get; set; }
        public bool IsEarly { get; set; }
    
        public virtual Duty Duty { get; set; }
        public virtual Student Student { get; set; }
    }
}
