//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.RegisterTests = new HashSet<RegisterTest>();
        }
    
        public int ID { get; set; }
        public string TimePeriod { get; set; }
        public string FinalDate { get; set; }
        public string Test1 { get; set; }
        public int Department_Id { get; set; }
        public int Subject_Id { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterTest> RegisterTests { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
